//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Database : ModelI
{
    private Dictionary<int, Transaction> transactionDB = new Dictionary<int, Transaction>();
    private Dictionary<int, Rebate> rebateDB = new Dictionary<int, Rebate>();

    public void addTransaction(Transaction newT)
    {
        transactionDB.Add(newT.getID(), newT);
    }

    public Transaction getTransaction(int id)
    {
        Transaction current;
        if(transactionDB.TryGetValue(id, out current))
        {
            return current;
        } else
        {
            return null;
        }
    }

    public void addRebate(Rebate newR)
    {
        rebateDB.Add(newR.TransID, newR);
    }

    public Rebate getRebate(int id)
    {
        Rebate current;
        if(rebateDB.TryGetValue(id, out current))
        {
            return current;
        } else
        {
            return null;
        }
    }

    public int[] getKeys()
    {
        int[] keys = new int[rebateDB.Count];
        int i = 0;
        foreach(int key in rebateDB.Keys)
        {
            keys[i] = key;
            i++;
        }
        return keys;
    }

    public void removeRebate(int id)
    {
        rebateDB.Remove(id);
    }
}

