//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ModelI 
{
    Transaction getTransaction(int id);

	Rebate getRebate(int id);

	void addTransaction(Transaction newT);

    void addRebate(Rebate newR);

    int[] getKeys();

    void removeRebate(int id);
}

