//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Item
{
    private float price;
    private string name;
    private int amount;
    private bool returned;

    public float Price
    {
        get
        {
            return price;
        }
    }

    public bool Returned
    {
        set
        {
            return = value;
        }
    }

	public override string ToString()
	{
        string s = ("Item: " + name + "\nPrice: $" + price  + "\n");   
        if(returned)
        {
            s += "*** Returned ***\n";
        }
        return s;  
	}

	public Item(string n, float p)
	{
        name = n;
        price = p;
	}

}

