//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Manager
{
    public bool rebate = false;

    private TransactionDB transDB = new TransactionDB();

	public void returnItem(int id, string name)
	{
        transDB.getTransaction(id).Items[name].Returned = true;
	}

	public void addTransaction(int id)
	{
        transDB.addTransaction(id);
	}

	public void addItem(int id, string name, float price)
	{
        transDB.getTransaction(id).addItem(name, price);
	}

    public string genReceipt(int id)
    {
        return transDB.getTransaction(id).genReciept();
    }

	public string generateRebate()
	{
		if(rebate)
        {
            return "check here";
        }
        else
        {
            return "No rebate has been applied\n";
        }
	}

}

