//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Transaction
{
    private Dictionary<string, Item> items = new Dictionary<string, Item>();
    private int id;
    private Random rnd = new Random();

    public Dictionary<string, Item> Items
    {
        get
        {
            return items;
        }
    }

    public string genReciept()
	{
        int d = rnd.Next(1, 31);
        string s = "Date: 6/" + d + "/18\nID: " + id + "\n\n";
        float total = 0;
        foreach(Item i in items.Values)
        {
            s += i.ToString() + "\n";
            total += i.Price;
        }
        s += "Total: $" + total;
        return s;
	}

	public Transaction(int i)
	{
        id = i;
	}

	public void addItem(string n, float p)
	{
        items.Add(n, new Item(n, p));
	}

}

