//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UI
{
    private Manager manager = new Manager();
    private int itemNum = 0;

    private static void Main(string[] args)
	{
		throw new System.NotImplementedException();
	}

	private void mainScreen()
	{
        Console.WriteLine("(1) Create a Sales Transaction");
        Console.WriteLine("(2) Return Item(s)");
        Console.WriteLine("(3) Enter Rebate");
        Console.WriteLine("(4) Generate Rebate Check");
        string input = Console.ReadLine();
        if(input == "1")
        {
            transactionScreen();
        }
        else if(input == "2")
        {
            returnScreen();
        }
        else if(input == "3")
        {
            enterRebateScreen();
        }
        else if(input == "4")
        {
            genRebateScreen();
        }
        else
        {
            Console.WriteLine("Invalid input try again");
        }

    }

	private void transactionScreen()
	{
        string countinue = "y";
        manager.addTransaction(itemNum);
		while(countinue == "y")
        {
            Console.WriteLine("Enter Item Name: ");
            string name = Console.ReadLine();
            Console.WriteLine("Enter in the price: ");
            float price = float.Parse(Console.ReadLine());
            Console.WriteLine("Enter in another item (y)es (n)o");
            countinue = Console.ReadLine();
            manager.addItem(itemNum, name, price);
            itemNum++;
        }
        Console.WriteLine(manager.genReceipt(itemNum));
	}

	private void returnScreen()
	{
		throw new System.NotImplementedException();
	}

	private void enterRebateScreen()
	{
		throw new System.NotImplementedException();
	}

	private void genRebateScreen()
	{
		throw new System.NotImplementedException();
	}

}

