//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Project_4.GeneratedCode;

public class RebateManager
{
    public delegate void EnterRebateHandler(int id, DateTime date);
    public delegate void GenRebateHandler();

    Rebate rebate = new Rebate();
    private DateTime deadline = new DateTime(2018, 7, 15);
    EnterRebateHandler enterRebateHandler;
    GenRebateHandler genRebateHandler;

    RebateOutputView.Observer updateRebateOutput;
    uxForm.Observer updateGenerateRebateOutput;
    ModelI dataBase;

    public RebateManager(ModelI d)
    {
        dataBase = d;
        enterRebateHandler = new EnterRebateHandler(enterRebate);
        genRebateHandler = new GenRebateHandler(genRebate);
    }

	public void enterRebate(int id, DateTime date)
	{
        bool valid = false;

        if (date.CompareTo(deadline) != 1)
        {
            Transaction user = dataBase.getTransaction(id);
            if (user != null)
            {
                valid = true;
                float percentage = (float)11 / 100;
                rebate.RebateAmount = user.Total * percentage;
                rebate.TransID = id;
                dataBase.addRebate(rebate);
                user.Rebate = true;
            }

        }
        updateRebateOutput(valid);
    }

	public void genRebate()
	{
        int[] keys = dataBase.getKeys();
        for(int i = 0; i < keys.Length; i++)
        {
            updateGenerateRebateOutput(keys[i]);
            dataBase.removeRebate(keys[i]);         
        }
    }

    internal void register(RebateOutputView.Observer run1, uxForm.Observer run2)
    {
        updateRebateOutput = run1;
        updateGenerateRebateOutput = run2;
    }
}

